spring:
    datasource:
        url: jdbc:mysql://34.64.182.191:3306/gilgeorigoreuda?characterEncoding=UTF-8
        username: root
        password: 1234

    jpa:
      hibernate:

        ddl-auto: update

      show-sql: true
      properties:
        hibernate:
          format_sql: true

cloud:
  aws:
    credentials:
      accessKey: AKIAYEKHUA7HVZMVYI7T
      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false