spring:
    datasource:
        url: jdbc:mysql://localhost:3306/gilgeorigoreuda?characterEncoding=UTF-8
        username: root
        password: 1234

    jpa:
      hibernate:

        ddl-auto: update

      show-sql: true
      properties:
        hibernate:
          format_sql: true

cloud:
  aws:
    credentials:
      accessKey: abb
      secretKey: abb
    region:
      static: ap-northeast-2
    stack:
      auto: false