spring:
    datasource:
        url: jdbc:mysql://localhost:3306/gilgeorigoreuda?characterEncoding=UTF-8
        username: root
        password: 1234

    jpa:
      hibernate:

        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    batch:
      job:
        enabled: false
      jdbc:
        initialize-schema: embedded

cloud:
  aws:
    credentials:
      accessKey: AKIAYEKHUA7HSDWVE5HD
      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: gilgeorigoreuda
      folder: dev/
