spring:
    datasource:
        url: jdbc:mysql://34.64.193.39:3306/gilgeorigoreuda?characterEncoding=UTF-8
        username: root
        password: rlatnehd@123

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

cloud:
  aws:
    credentials:
      accessKey: AKIAYEKHUA7HSDWVE5HD
      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: gilgeorigoreuda
      folder: dev/

oauth2:
  provider:
    kakao:
      client-id: dd83fb5281e50c8508ffc20b8dc07799
      redirect-url: http://localhost:8080/oauth2/callback/kakao
      token-url: https://kauth.kakao.com/oauth/token
      user-info-url: https://kapi.kakao.com/v2/user/me

security:
  jwt:
    secret-key: gilgeorigoreudagilgeorigoreudagilgeorigoreudagilgeorigoreuda
    access-expiration-time: 3600000 # 1시간
    refresh-expiration-time: 86400000 # 24시간

