spring:
    datasource:
        url: jdbc:mysql://localhost:3306/gilgeorigoreuda?characterEncoding=UTF-8
        username: root
        password: rlatnehd@123

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true