spring:
    datasource:
        url: jdbc:mysql://34.64.193.39:3306/gilgeorigoreuda?characterEncoding=UTF-8
        username: root
        password: rlatnehd@123

    jpa:
      hibernate:

        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

cloud:
  aws:
    #    credentials:
    #      accessKey: AKIAYEKHUA7HVZMVYI7T
    #      secretKey: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: gilgeorigoreuda
      folder: dev
