version: "3"
services:
  mysqldb:
    container_name: mysql-dev-db
    image: mysql
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_DATABASE: gilgeorigoreuda
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql